name: Deploy

on:
    push:
        branches:
            - main

jobs:
    deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout main branch
              uses: actions/checkout@v3
              with:
                path: site
            
            - name: Remove .git folder
              run: |
                rm -r site/.git
                ls -la

            - name: Copy site to server
              uses: garygrossgarten/github-action-scp@release
              with:
                local: site
                remote: /var/www/root/public_html
                rmRemote: true
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                password: ${{ secrets.PASSWORD }}
