name: Deploy

on:
    push:
        branches:
            - main

jobs:
    deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout main branch
              uses: actions/checkout@v3
            
            - name: Copy site to server
              uses: garygrossgarten/github-action-scp@release
              with:
                local: $GITHUB_WORKSPACE
                remote: /var/www/html/root/public_html
                rmRemote: true
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                password: ${{ secrets.PASSWORD }}
