name: Deploy

on:
    push:
        branches:
            - main

jobs:
    deployment:
        runs-on: self-hosted
        steps:
            - name: Checkout main branch
              uses: actions/checkout@v3
            
            - name: Remove old files
              uses: JesseTG/rm@v1.0.3
              with:
                path: /var/www/root/public_html/**
                
            - name: Install new site
              uses: canastro/copy-file-action@0.0.2
              with:
                source: "$GITHUB_WORKSPACE"
                target: "/var/www/root/public_html/"
